### ISSUE TITLE
Add entities instead of attributes of the main entity

### ISSUE THREAD

**Issue by marcinbauer85** [custom-components/places#166]
Is it possible to have all attributes as seperate entities of the Places integration? I would like to use some attributes as card data, and currently this can be only achieved with the Entity card or a Template card.

**Comment by Snuffy2** [comment]
I don't think that is something I plan to switch to for `places`. There are so many attributes, it would generate a ton of sensors. It would also require a large rewrite to change it from a single entity to a device with multiple entities. 

For now, if you want to create an entity for an attribute, you can do it yourself with a [template](https://www.home-assistant.io/integrations/template/).

Example:
```yaml
template:
  - sensor:
    - name: "Snuffy2s Direction of Travel"
      unique_id: snuffy2s_direction_of_travel
      state: >
        {{ state_attr('sensor.snuffy2s_place','direction_of_travel') }}
```
