### ISSUE TITLE
iPhone message "Failed to load attachment, Unrecognized attachment file type"

### ISSUE THREAD

**Issue by haqthat** [custom-components/places#28]
Everything works for me, but the included map is not working.
I get the alerts, just the top of the alert says "Failed to load attachment, Unrecognized attachment file type"

![notification](https://user-images.githubusercontent.com/1305090/134729143-5fdda9e3-c1c8-41b2-a065-1a091f1272ce.png)

automations.yaml
```
- alias: ReverseLocate
  initial_state: 'on'
  trigger:
    platform: event
    event_type: places_state_update
  condition:
    condition: template
    value_template: '{{ trigger.event.data.entity == "Person" }}'
  action:
  - service: notify.mobile_app_iphone
    data_template:
      title: 'ReverseLocate: {{ trigger.event.data.entity }} ({{ trigger.event.data.devicetracker_zone }}) {{ trigger.event.data.place_name }}'
      message: |-
        {{ trigger.event.data.entity }} ({{ trigger.event.data.devicetracker_zone }}) 
        {{ trigger.event.data.place_name }}
        {{ trigger.event.data.distance_from_home }} from home and traveling {{ trigger.event.data.direction }}
        {{ trigger.event.data.to_state }} ({{ trigger.event.data.mtime }})
      data:
        attachment:
          url: '{{ trigger.event.data.map }}'
          hide_thumbnail: false
```

configuaration.yaml
```sensor places_person:
  - platform: places
    name: Person
    devicetracker_id: device_tracker.person_iphone
    options: place,zone
    #display_zone: show
    map_provider: google
    map_zoom: 19
    home_zone: zone.home
    api_key: person@gmail.com
```
